Repository openshift/configuration-anomaly-detection, pull requests merged in 2023-07, with the labels that each got.

#194 OSD-13697: Add ClusterProvisioningDelay investigation
  cadctl/cmd/investigate/investigate.go
  cadctl/cmd/root.go
  pkg/aws/aws.go
  pkg/investigation/investigation.go
  pkg/logging/logging.go
  pkg/ocm/ocm.go
  pkg/pagerduty/mock/pagerdutymock.go
  pkg/pagerduty/pagerduty.go
  pkg/services/assumerole/assumerole.go
  pkg/services/ccam/ccam.go
  pkg/services/chgm/chgm.go
  pkg/services/chgm/chgm_test.go
  pkg/services/cpd/cpd.go
  pkg/services/cpd/cpd_test.go
  pkg/services/networkverifier/networkverifier.go
  pkg/utils/utils.go
Labels: approved, lgtm, jira/valid-reference

#195 OSD-16112: Improve linting
  .editorconfig
  .golangci.yml
  Makefile
  cadctl/cmd/investigate/investigate.go
  hack/pre-commit.sh
  hack/update-template/main.go
  pkg/aws/aws.go
  pkg/aws/aws_test.go
  pkg/ocm/ocm_config.go
  pkg/pagerduty/errors.go
  pkg/pagerduty/pagerduty.go
  pkg/pagerduty/pagerduty_test.go
  pkg/services/ccam/ccam.go
  pkg/services/chgm/chgm.go
  pkg/services/chgm/chgm_test.go
  pkg/services/cpd/cpd.go
  pkg/services/networkverifier/networkverifier.go
  pkg/services/networkverifier/networkverifier_test.go
Labels: approved, lgtm, jira/valid-reference

#197 Fix: add missing returns to ccam switch
  pkg/services/ccam/ccam.go
Labels: approved, lgtm

#196 Add remaining checks from 'osdctl cluster cpd' to cpd investigation
  pkg/aws/aws.go
  pkg/aws/mock/aws.go
  pkg/services/cpd/cpd.go
Labels: approved, lgtm

#198 fix: OSD-17489 empty external cluster id
  cadctl/cmd/investigate/investigate.go
  pkg/ocm/ocm.go
Labels: approved, lgtm

#199 Normalize default cluster ID to internal-id
  cadctl/cmd/investigate/investigate.go
  pkg/ocm/mock/ocmmock.go
  pkg/ocm/ocm.go
Labels: approved, lgtm

#200 Build CPD pagerduty note to contain all checks
  pkg/services/cpd/cpd.go
Labels: approved, lgtm

#202 Improve log readibility
  cadctl/cmd/investigate/investigate.go
  pkg/pagerduty/pagerduty.go
Labels: approved, lgtm

#203 Bump networkverifier from 0.2.2 to 0.3.1
  go.mod
  go.sum
Labels: approved, lgtm

#204 OSD-17516: Return early when checking default routes
  pkg/services/cpd/cpd.go
Labels: approved, lgtm, jira/valid-reference

#205 Rename 'service' notion to 'investigation'
  CONTRIBUTING.md
  cadctl/cmd/investigate/investigate.go
  pkg/aws/assumerole/assumerole.go
  pkg/investigations/ccam/ccam.go
  pkg/investigations/ccam/ccam_suite_test.go
  pkg/investigations/chgm/chgm.go
  pkg/investigations/chgm/chgm_suite_test.go
  pkg/investigations/chgm/chgm_test.go
  pkg/investigations/cpd/cpd.go
  pkg/investigations/cpd/cpd_test.go
  pkg/investigations/investigation.go
  pkg/networkverifier/networkverifier.go
  pkg/networkverifier/networkverifier_test.go
Labels: approved, lgtm

#206 Fix timeout of network verifier and refactor initialization of network verifier
  go.mod
  go.sum
  pkg/aws/mock/cloudtrailmock.go
  pkg/aws/mock/ec2mock.go
  pkg/investigations/chgm/chgm_test.go
  pkg/networkverifier/networkverifier.go
Labels: approved, lgtm

#207 Remove antipattern tests that test our imports
  pkg/aws/aws.go
  pkg/aws/aws_suite_test.go
  pkg/aws/aws_test.go
  pkg/aws/mock/cloudtrailmock.go
  pkg/aws/mock/ec2mock.go
  pkg/aws/mock/stsmock.go
Labels: approved, lgtm

#210 OSD-17220: Add CPD stage service in service switch
  cadctl/cmd/investigate/investigate.go
Labels: approved, lgtm, jira/valid-reference

#208 OSD-17456 Add alert handling for hypershift SilenceAlerts
  cadctl/cmd/investigate/investigate.go
  pkg/investigations/investigation.go
  pkg/investigations/silencealerts/silencealerts.go
  pkg/logging/logging.go
  pkg/networkverifier/networkverifier.go
  pkg/pagerduty/mock/pagerdutymock.go
  pkg/pagerduty/pagerduty.go
  pkg/pagerduty/pagerduty_test.go
Labels: approved, lgtm, tide/merge-method-squash
