Repository openshift/configuration-anomaly-detection, pull requests merged in 2024-01, with the labels that each got.

#246 OSD-19710 Replace node shutdown limited support with service log
  .gitignore
  cadctl/cmd/investigate/investigate.go
  images/cad_chgm_investigation/chgm_investigation.excalidraw
  images/cad_chgm_investigation/chgm_investigation_dark.png
  images/cad_chgm_investigation/chgm_investigation_light.png
  pkg/aws/aws.go
  pkg/investigations/ccam/ccam.go
  pkg/investigations/chgm/chgm.go
  pkg/investigations/chgm/chgm_test.go
  pkg/investigations/cpd/cpd.go
  pkg/investigations/investigation.go
  pkg/metrics/metrics.go
  pkg/ocm/mock/ocmmock.go
  pkg/ocm/ocm.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  test/ocm_test.json
  test/ocm_test_invalid.json
Labels: approved, lgtm, tide/merge-method-squash

#253 Fix network verifier success log message for CHGM
  pkg/investigations/chgm/chgm.go
Labels: approved, lgtm

#254 Post network verifier run failure at the end of investigation
  pkg/investigations/chgm/chgm.go
  pkg/investigations/chgm/chgm_test.go
Labels: approved, lgtm

#255 OSD-20190: automatically send network SL for chgms
  pkg/investigations/chgm/chgm.go
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference
