Repository openshift/configuration-anomaly-detection, pull requests merged in 2024-04, with the labels that each got.

#263 OSD-22320: Update SL severities to match OCM guidelines
  pkg/investigations/chgm/chgm.go
  pkg/investigations/chgm/chgm_test.go
  pkg/investigations/cpd/cpd.go
Labels: approved, lgtm, jira/valid-reference

#266 OSD-22395: Passing the KMS key defined for the cluster (if any) to osd-network-verifier
  pkg/networkverifier/networkverifier.go
  pkg/networkverifier/networkverifier_suite_test.go
  pkg/networkverifier/networkverifier_test.go
Labels: approved, lgtm, jira/valid-reference

#267 OSD-22496: add scc workaround
  openshift/SRVKP-437-workaround-template.yaml
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#268 fix SRVKP cronjob image
  openshift/SRVKP-437-workaround-template.yaml
Labels: approved, lgtm

#265 Upgraded golang/x/net to 0.24 to fix vuln
  go.mod
  go.sum
Labels: approved, lgtm

#269 Cleanup: remove workaround cronjob template
  openshift/SRVKP-437-workaround-template.yaml
Labels: approved, lgtm
