Repository openshift/configuration-anomaly-detection, pull requests merged in 2024-05, with the labels that each got.

#273 Bump builder image to golang 1.21
  Dockerfile
Labels: approved, lgtm

#271 Bump go to 1.21
  .ci-operator.yaml
  .golangci.yml
  Makefile
  boilerplate/_data/backing-image-tag
  boilerplate/_data/last-boilerplate-commit
  boilerplate/_lib/subscriber-report
  boilerplate/openshift/osd-container-image/standard.mk
  go.mod
  go.sum
  hack/update-template/main.go
  pkg/investigations/investigation.go
Labels: approved, lgtm

#272 Set resource limits to all containers
  deploy/pipeline-trigger.yaml
  deploy/task-cad-checks.yaml
  deploy/tekton-pruner.yaml
  openshift/template.yaml
Labels: approved, lgtm

#275 Fix invalid tekton step definition
  deploy/task-cad-checks.yaml
  openshift/template.yaml
Labels: approved, lgtm

#262 OSD-21053: update dashboard to point at appsrep07ue1
  dashboards/grafana-dashboard-configuration-anomaly-detection.configmap.yaml
Labels: approved, lgtm, jira/valid-reference

#277 OSD-17681 Refactor entrypoint to facilitate adding new investigations
  CONTRIBUTING.md
  README.md
  cadctl/cmd/investigate/investigate.go
  pkg/investigations/ccam/ccam.go
  pkg/investigations/chgm/chgm.go
  pkg/investigations/chgm/chgm_test.go
  pkg/investigations/cpd/cpd.go
  pkg/investigations/investigation.go
  pkg/metrics/metrics.go
  pkg/pagerduty/mock/pagerdutymock.go
  pkg/pagerduty/pagerduty.go
  test/generate_incident.sh
Labels: approved, lgtm, tide/merge-method-squash

#283 maint: add notewriter instead of building strings via sb directly
  pkg/investigations/chgm/chgm.go
  pkg/investigations/cpd/cpd.go
  pkg/notewriter/notewriter.go
  pkg/notewriter/notewriter_test.go
Labels: approved, lgtm

#282 Add kube-client
  cadctl/cmd/investigate/investigate.go
  go.mod
  go.sum
  pkg/k8s/client.go
  pkg/logging/logging.go
  pkg/managedcloud/managedcloud.go
Labels: approved, lgtm, tide/merge-method-squash

#285 Fix(OSD-23693): correctly handle backplane-cli errors for the used backplane-cli version
  pkg/investigations/ccam/ccam.go
Labels: approved, lgtm

#279 PoC: Investigate ClusterMonitoringErrorBudgetBurn due to a misconfigured UWM configmap
  cadctl/cmd/investigate/investigate.go
  pkg/investigations/clustermonitoringerrorbudgetburn/clustermonitoringerrorbudgetburn.go
  pkg/investigations/clustermonitoringerrorbudgetburn/clustermonitoringerrorbudgetburn_test.go
  test/generate_incident.sh
Labels: approved, lgtm

#286 Fix(OSD-23693): wrong string to determine installer assumerole failure
  pkg/investigations/ccam/ccam.go
Labels: approved, lgtm
