Repository openshift/configuration-anomaly-detection, pull requests merged in 2025-05, with the labels that each got.

#430 Create CAD remediation for UpgradeConfigSyncFailureOver4HrSRE
  pkg/investigations/registry.go
  pkg/investigations/upgradeconfigsyncfailureover4hr/README.md
  pkg/investigations/upgradeconfigsyncfailureover4hr/upgradeconfigsyncfailureover4hr.go
  pkg/investigations/upgradeconfigsyncfailureover4hr/upgradeconfigsyncfailureover4hr_test.go
  pkg/ocm/ocm.go
Labels: approved, lgtm, tide/merge-method-squash

#395 OSD-28525 - Initial implementation for MachineHealthCheckUnterminatedShortCircuitSRE investigation
  go.mod
  pkg/investigations/machinehealthcheckunterminatedshortcircuitsre/machinehealthcheckunterminatedshortcircuitsre.go
  pkg/investigations/machinehealthcheckunterminatedshortcircuitsre/machinehealthcheckunterminatedshortcircuitsre_test.go
  pkg/investigations/machinehealthcheckunterminatedshortcircuitsre/metadata.yaml
  pkg/investigations/machinehealthcheckunterminatedshortcircuitsre/recommendation.go
  pkg/investigations/machinehealthcheckunterminatedshortcircuitsre/testing/README.md
  pkg/investigations/machinehealthcheckunterminatedshortcircuitsre/testing/srep-worker-healthcheck_machinehealthcheck.yaml
  pkg/investigations/machinehealthcheckunterminatedshortcircuitsre/testing/unstoppable_pdb.yaml
  pkg/investigations/machinehealthcheckunterminatedshortcircuitsre/testing/unstoppable_workload.yaml
  pkg/investigations/registry.go
  pkg/investigations/utils/machine/machine.go
  pkg/investigations/utils/machine/machine_test.go
  pkg/investigations/utils/node/node.go
  pkg/investigations/utils/node/node_test.go
  pkg/k8s/scheme.go
  test/generate_incident.sh
Labels: approved, lgtm

#435 Fix: machinehealthcheckunterminatedshortcircuitsre k8s client setup
  pkg/investigations/machinehealthcheckunterminatedshortcircuitsre/machinehealthcheckunterminatedshortcircuitsre.go
Labels: approved, lgtm

#436 Fix: ignore non-existant clusters
  cadctl/cmd/investigate/investigate.go
Labels: approved, lgtm

#431 OSD-29468: Configuration Anomaly Detection - E2E Test - Blocked Egress/ No Known MIsconfiguration
  pkg/aws/aws.go
  test/e2e/aws.go
  test/e2e/configuration_anomaly_detection_test.go
  test/e2e/utils.go
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#427 OSD-29208 - Remove CAD template file generation
  Makefile
  README.md
  deploy/README.md
  deploy/interceptor.yaml
  deploy/namespace/README.md
  deploy/namespace/namespace.yaml
  deploy/pipeline-trigger.yaml
  deploy/pipeline.yaml
  deploy/resource-quota.yaml
  deploy/serviceaccount.yaml
  deploy/skip-webhook/README.md
  deploy/skip-webhook/pipeline-run.yaml
  deploy/task-cad-checks-secrets-backplane.yaml
  deploy/task-cad-checks-secrets-ocm-client.yaml
  deploy/task-cad-checks-secrets-pd.yaml
  deploy/task-cad-checks.yaml
  deploy/tekton-pruner.yaml
  deploy/tekton/README.md
  deploy/tekton/pipeline-operator-subscription.yaml
  hack/update-template/.gitignore
  hack/update-template/README.md
  hack/update-template/go.mod
  hack/update-template/go.sum
  hack/update-template/main.go
  hack/update-template/types.go
  hack/update-template/unstructured-modification.go
  openshift/template.yaml
Labels: approved, lgtm

#438 Experimental POC: add k8sgpt permissions
  pkg/investigations/aitest/README.md
  pkg/investigations/aitest/metadata.yaml
  pkg/investigations/aitest/testing/README.md
Labels: approved, lgtm, tide/merge-method-squash

#439 K8sgpt poc
  .gitignore
  Makefile
  README.md
  go.mod
  go.sum
  interceptor/go.mod
  interceptor/go.sum
  openshift/template.yaml
  pkg/ai/k8sgpt/k8sgpt.go
  pkg/investigations/apierrorbudgetburn/README.md
  pkg/investigations/apierrorbudgetburn/apierrorbudgetburn.go
  pkg/investigations/apierrorbudgetburn/metadata.yaml
  pkg/investigations/apierrorbudgetburn/testing/README.md
  pkg/investigations/registry.go
  pkg/k8s/client.go
  test/generate_incident.sh
Labels: approved, lgtm, tide/merge-method-squash

#440 Fix security context for tekton resource pruner
  openshift/template.yaml
Labels: approved, lgtm

#442 Add seccompProfile RuntimeDefault to tekton pruner job
  openshift/template.yaml
Labels: approved, lgtm

#443 Fix tekton resource pruner scc by using defaults
  openshift/template.yaml
Labels: approved, lgtm

#444 SREP-21: backplane API is now allocating a remediation instance id for each call to createRemediation
  go.mod
  go.sum
  interceptor/go.mod
  interceptor/go.sum
  interceptor/test/e2e.sh
  pkg/investigations/apierrorbudgetburn/apierrorbudgetburn.go
  pkg/investigations/clustermonitoringerrorbudgetburn/clustermonitoringerrorbudgetburn.go
  pkg/investigations/insightsoperatordown/insightsoperatordown.go
  pkg/investigations/machinehealthcheckunterminatedshortcircuitsre/machinehealthcheckunterminatedshortcircuitsre.go
  pkg/investigations/machinehealthcheckunterminatedshortcircuitsre/machinehealthcheckunterminatedshortcircuitsre_test.go
  pkg/investigations/upgradeconfigsyncfailureover4hr/upgradeconfigsyncfailureover4hr.go
  pkg/k8s/client.go
  test/generate_incident.sh
Labels: approved, lgtm, jira/valid-reference

#445 OSD-28525 - make MachineHealthCheckShortCircuitUnterminatedSRE investigation non-experimental
  pkg/investigations/machinehealthcheckunterminatedshortcircuitsre/machinehealthcheckunterminatedshortcircuitsre.go
Labels: approved, lgtm

#446 Making sure backplane-cli uses the OCM connection created by CAD
  go.mod
  go.sum
  interceptor/go.mod
  interceptor/go.sum
Labels: approved, lgtm

#447 Fix: pass AWS proxy explicitly
  pkg/aws/aws.go
  pkg/aws/aws_test.go
  pkg/aws/mock/aws.go
  pkg/investigations/chgm/chgm_test.go
  pkg/managedcloud/managedcloud.go
  pkg/networkverifier/networkverifier.go
  test/set_stage_env.sh
Labels: approved, lgtm

#448 fix e2e test blocking build
  test/e2e/configuration_anomaly_detection_test.go
Labels: approved, lgtm

#449 Update backplane-cli dependency.
  go.mod
  go.sum
  interceptor/go.mod
  interceptor/go.sum
Labels: approved, lgtm

#450 Fix obtaining of "experimental enabled" env variable
  cadctl/cmd/investigate/investigate.go
  interceptor/pkg/interceptor/pdinterceptor.go
Labels: approved, lgtm

#451 Update to latest backplane-cli.
  go.mod
  go.sum
  interceptor/go.mod
  interceptor/go.sum
Labels: approved, lgtm

#441 OSD-29470: To create E2E Tests for CAD - Cluster has gone missing - Infra Nodes turned off
  go.mod
  test/e2e/configuration_anomaly_detection_test.go
  test/e2e/utils/aws.go
  test/e2e/utils/generate_incident.go
  test/e2e/utils/utils.go
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#453 OSD-28972: Updated github actions workflow to support dependabot PRs
  .github/workflows/auto-tidy-interceptor.yml
Labels: approved, lgtm, jira/valid-reference

#404 OSD-18645 - Initial implementation for CannotRetrieveUpdatesSRE
  pkg/investigations/cannotretrieveupdatessre/README.md
  pkg/investigations/cannotretrieveupdatessre/cannotretrieveupdatessre.go
  pkg/investigations/cannotretrieveupdatessre/cannotretrieveupdatessre_test.go
  pkg/investigations/cannotretrieveupdatessre/metadata.yaml
  pkg/investigations/cannotretrieveupdatessre/testing/README.md
  pkg/investigations/registry.go
  test/generate_incident.sh
Labels: approved, lgtm

#460 SREP-207: Naming cad-interceptor-service service port so it can be referenced by the ServiceMonitor
  openshift/template.yaml
Labels: approved, lgtm, jira/valid-reference

#462 Fix bug SREP-652: User's incorrectly reporting as not banned.
  pkg/ocm/ocm.go
  test/generate_incident.sh
Labels: approved, lgtm, jira/valid-reference
