Repository openshift/configuration-anomaly-detection, pull requests merged in 2025-07, with the labels that each got.

#498 boilerplating e2e suite
  .github/dependabot.yml
  Makefile
  OWNERS_ALIASES
  boilerplate/_data/last-boilerplate-commit
  boilerplate/generated-includes.mk
  boilerplate/openshift/golang-osd-e2e/OWNERS
  boilerplate/openshift/golang-osd-e2e/README.md
  boilerplate/openshift/golang-osd-e2e/e2e-template.yml
  boilerplate/openshift/golang-osd-e2e/project.mk
  boilerplate/openshift/golang-osd-e2e/standard.mk
  boilerplate/openshift/golang-osd-e2e/update
  boilerplate/openshift/osd-container-image/OWNERS_ALIASES
  boilerplate/update.cfg
  config/config.go
  test/e2e/Dockerfile
  test/e2e/README.md
  test/e2e/configuration_anomaly_detection_runner_test.go
  test/e2e/configuration_anomaly_detection_tests.go
  test/e2e/e2e-template.yml
  test/e2e/project.mk
Labels: approved, lgtm, tide/merge-method-squash

#507 Moves environment variables to the beggining of the investigation and interceptor
  cadctl/cmd/investigate/investigate.go
  interceptor/main.go
  pkg/investigations/chgm/chgm_test.go
  pkg/logging/logging.go
Labels: approved, lgtm

#503 Merge interceptor module into root Go module
  .github/workflows/auto-tidy-interceptor.yml
  go.mod
  go.sum
  interceptor/go.mod
  interceptor/go.sum
Labels: approved, lgtm

#511 SREP-1011: Fixing dependency on OCM TOKEN for CAD E2E Tests
  go.mod
  go.sum
  test/e2e/configuration_anomaly_detection_tests.go
  test/e2e/utils/utils.go
Labels: approved, lgtm, jira/valid-reference

#514 Shortned the LS message to make it clearer
  pkg/investigations/chgm/chgm.go
Labels: approved, lgtm

#519 Fix typos in documentation
  README.md
  pkg/investigations/chgm/README.md
Labels: approved, lgtm

#512 Prevent script failure on empty client_id
  README.md
  test/launch_local_env.sh
Labels: approved, lgtm

#521 Revert k8sgpt integration due to maintenance overhead and CVE dependencies
  CLAUDE.md
  README.md
  go.mod
  go.sum
  pkg/ai/k8sgpt/k8sgpt.go
  pkg/investigations/aitest/README.md
  pkg/investigations/aitest/metadata.yaml
  pkg/investigations/aitest/testing/README.md
  pkg/investigations/apierrorbudgetburn/README.md
  pkg/investigations/apierrorbudgetburn/apierrorbudgetburn.go
  pkg/investigations/apierrorbudgetburn/metadata.yaml
  pkg/investigations/apierrorbudgetburn/testing/README.md
  pkg/investigations/registry.go
  test/e2e/utils/generate_incident.go
  test/generate_incident.sh
Labels: approved, lgtm

#505 [SREP-600] Use a builder pattern to initialize resources used by investigations.
  cadctl/cmd/investigate/investigate.go
  pkg/investigations/cannotretrieveupdatessre/cannotretrieveupdatessre.go
  pkg/investigations/ccam/ccam.go
  pkg/investigations/ccam/ccam_test.go
  pkg/investigations/chgm/chgm.go
  pkg/investigations/chgm/chgm_test.go
  pkg/investigations/clustermonitoringerrorbudgetburn/clustermonitoringerrorbudgetburn.go
  pkg/investigations/cpd/cpd.go
  pkg/investigations/insightsoperatordown/insightsoperatordown.go
  pkg/investigations/investigation/investigation.go
  pkg/investigations/machinehealthcheckunterminatedshortcircuitsre/machinehealthcheckunterminatedshortcircuitsre.go
  pkg/investigations/precheck/precheck.go
  pkg/investigations/precheck/precheck_test.go
  pkg/investigations/upgradeconfigsyncfailureover4hr/upgradeconfigsyncfailureover4hr.go
Labels: approved, lgtm
