Repository openshift/configuration-anomaly-detection, pull requests merged in 2025-04, with the labels that each got.

#397 OSD-28224 - cad should always post failures to the incident notes
  cadctl/cmd/investigate/investigate.go
  hack/bootstrap-investigation.sh
  pkg/investigations/chgm/chgm.go
  pkg/investigations/clustermonitoringerrorbudgetburn/clustermonitoringerrorbudgetburn.go
  pkg/investigations/cpd/cpd.go
  pkg/investigations/investigation/investigation.go
Labels: approved, lgtm

#393 OSD-27752: Deprecate x-secret-token
  README.md
  deploy/README.md
  deploy/pipeline-trigger.yaml
  deploy/task-cad-checks-secrets-pd.yaml
  openshift/template.yaml
Labels: approved, lgtm, jira/valid-reference

#399 OSD-28224: Add nil safety to handleCADFailure
  cadctl/cmd/investigate/investigate.go
Labels: approved, lgtm, jira/valid-reference

#400 fix stage env script after removing aws creds from vault
  test/set_stage_env.sh
Labels: approved, lgtm

#402 fix: ClusterProvisioningDelay servicelog templating
  pkg/investigations/cpd/cpd.go
Labels: approved, lgtm

#380 Add insights operator down investigation
  pkg/investigations/insightsoperatordown/insightsoperatordown.go
  pkg/investigations/insightsoperatordown/insightsoperatordown_test.go
  pkg/investigations/insightsoperatordown/testing/README.md
  pkg/investigations/insightsoperatordown/testing/block-api-openshift.sh
  pkg/investigations/registry.go
  pkg/ocm/ocm.go
  test/generate_incident.sh
Labels: approved, lgtm

#406 Bump osd-network-verifier to v1.2.3
  go.mod
  go.sum
  interceptor/go.mod
  interceptor/go.sum
Labels: approved, lgtm, tide/merge-method-squash

#414 OSD-28971 : Fix configuration-anomaly-detection dashboards
  dashboards/grafana-dashboard-configuration-anomaly-detection.configmap.yaml
Labels: approved, lgtm

#416 OSD-29402: Increase the default network-verifier timeout from 2s to 5s
  pkg/networkverifier/networkverifier.go
Labels: approved, lgtm, jira/valid-reference

#419 feat(SDE-4821): base e2e test configuration
  Makefile
  go.mod
  go.sum
  interceptor/go.mod
  interceptor/go.sum
  test/e2e/Dockerfile
  test/e2e/configuration_anomaly_detection_runner_test.go
  test/e2e/configuration_anomaly_detection_test.go
  test/e2e/project.mk
  test/e2e/test-e2e-suite-template.yml
Labels: approved, lgtm, tide/merge-method-squash

#420 Update gitignore to trigger a build for e2e
  .gitignore
Labels: approved, lgtm

#421 Make tekton pruner image configurable via app-interface
  deploy/tekton-pruner.yaml
  hack/update-template/main.go
  openshift/template.yaml
Labels: approved, lgtm

#424 OSD-29424 - Update PD incident title after investigation
  cadctl/cmd/investigate/investigate.go
  pkg/pagerduty/mock/pagerdutymock.go
  pkg/pagerduty/pagerduty.go
Labels: approved, lgtm

#425 OSD-29424 - Bugfix to use `pagerdutyTitlePrefix` instead of hardcoded string when updating incident title
  cadctl/cmd/investigate/investigate.go
Labels: approved, lgtm

#423 OSD-28476: CAD puts CHGM in limited support if instances were stopped…
  pkg/investigations/chgm/chgm.go
  pkg/investigations/chgm/chgm_test.go
Labels: approved, lgtm, jira/valid-reference

#426 Maint: handle degraded api when creating k8sclient
  go.mod
  pkg/investigations/clustermonitoringerrorbudgetburn/clustermonitoringerrorbudgetburn.go
  pkg/investigations/insightsoperatordown/insightsoperatordown.go
  pkg/k8s/client.go
  pkg/k8s/errors.go
  pkg/k8s/errors_test.go
  pkg/k8s/scheme.go
Labels: approved, lgtm, tide/merge-method-squash

#429 OSD-28525 - Additional permission for CAD to retrieve machinehealthchecks on-cluster
  pkg/investigations/machineHealthCheckUnterminatedShortCircuitSRE/metadata.yaml
Labels: approved, lgtm
