Repository openshift/configuration-anomaly-detection, pull requests merged in 2025-06, with the labels that each got.

#471 Add PR template
  .github/pull_request_template.md
Labels: approved, lgtm

#455 OSD-30032: To Add E2E test for InsightsOperatorDown
  test/e2e/configuration_anomaly_detection_test.go
Labels: approved, lgtm, tide/merge-method-squash, jira/valid-reference

#477 Revert "SREP-702: Add PR check for unit tests"
  Makefile
  hack/investigation-test-coverage.sh
Labels: approved, lgtm, jira/valid-reference

#492 Remove not used to debug option
  cadctl/cmd/investigate/investigate.go
  pkg/ocm/ocm.go
Labels: approved, lgtm

#476 OSD-30036: To create E2E Test for CAD - Cluster has gone missing - UpgradeConfigSyncFailureOver4Hr
  test/e2e/configuration_anomaly_detection_test.go
  test/e2e/utils/generate_incident.go
  test/e2e/utils/utils.go
Labels: approved, lgtm, jira/valid-reference
